### ISSUE TITLE
Upstream changed to BSD 3-Clause

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyusb-feedstock#1]
xref: https://github.com/pyusb/pyusb/pull/281

**Comment by jakirkham** [comment]
cc @conda-forge/pyusb

**Comment by hmaarrfk** [comment]
whats the issue exactly? the meta already specifies BSD-3 Clause
![image](https://user-images.githubusercontent.com/90008/78198928-10b0b800-743f-11ea-916b-0f5017405e77.png)

**Comment by jakirkham** [comment]
There actually is no released version under BSD-3-Clause. Current and AFAIK previous versions are under Apache 2.0. So that's actually not correct.

That said, once they make a new release we can say BSD-3-Clause.

Please see xref in OP for details.

**Comment by jakirkham** [comment]
Actually it looks like the Apache 2.0 license bit [doesn't show up in 1.0.2]( https://github.com/pyusb/pyusb/blob/v1.0.2/LICENSE ) and they already went back to BSD-3-Clause. So it looks like this was a false alarm. Sorry for the noise.

**Comment by hmaarrfk** [comment]
ah, thats ok, no problem.
